name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/lib/flutter-setup.yaml
      - run: flutter pub get
      - run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/lib/flutter-setup.yaml
      - run: flutter pub get
      - run: flutter test
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/lib/flutter-setup.yaml
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: ./.github/lib/flutter-setup.yaml
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
